<a href="https://colab.research.google.com/github/RamonNicolas/DataPy/blob/main/Py_DS_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color=green> PYTHON PARA DATA SCIENCE - NUMPY
---

# <font color=green> 1. INTRODUÇÃO AO PYTHON
---

# 1.1 Introdução

> Python é uma linguagem de programação de alto nível com suporte a múltiplos paradigmas de programação. É um projeto *open source* e desde seu surgimento, em 1991, vem se tornando uma das linguagens de programação interpretadas mais populares. 
>
> Nos últimos anos Python desenvolveu uma comunidade ativa de processamento científico e análise de dados e vem se destacando como uma das linguagens mais relevantes quando o assunto é ciência de dados e machine learning, tanto no ambiente acadêmico como também no mercado.

# 1.2 Instalação e ambiente de desenvolvimento

### Instalação Local

### https://www.python.org/downloads/
### ou
### https://www.anaconda.com/distribution/

### Google Colaboratory

### https://colab.research.google.com

### Verificando versão

In [31]:
!python --version

Python 3.7.11


# 1.3 Trabalhando com arrays Numpy

In [2]:
import numpy as np


In [6]:
km = np.loadtxt('carros-km.txt')

In [8]:
anos = np.loadtxt('carros-anos.txt', dtype=int)

array([2003, 1991, 1990, 2019, 2006, 2012, 2019, 2009, 2010, 2011, 2002,
       2007, 2001, 2019, 2009, 2016, 2012, 2019, 2016, 2017, 2002, 2019,
       1994, 1991, 2019, 2019, 2016, 2019, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2019, 2019, 2009, 2019, 2013, 2003, 2019, 2002,
       2019, 2002, 2004, 2001, 2019, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2019, 2019, 2019, 2019, 2019, 2017, 2011, 2001, 1996,
       2019, 1994, 2019, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2019, 2019, 1999, 2007, 1993, 1995, 2019, 2019, 2016, 2011,
       2019, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2019, 2006, 2001, 2019, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2019, 2017, 2019, 2019, 2006, 2015, 2007,
       2005, 2017, 1998, 2019, 1999, 2019, 2009, 2003, 1994, 2019, 1994,
       2019, 2015, 1996, 1997, 1993, 2019, 1992, 1995, 2019, 1990, 2019,
       2019, 1991, 1990, 2012, 2007, 2013, 2000, 20

In [10]:
kmmedia = km/(2019-anos)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [13]:
type(kmmedia)

numpy.ndarray



```
## Isto` está formatado como código`
```

### Obtendo a quilometragem média por ano

# <font color=green> 2. CARACTERÍSTICAS BÁSICAS DA LINGUAGEM
---

# 2.1 Operações matemáticas

### Operadores aritméticos: $+$, $-$, $*$, $/$, $**$, $\%$, $//$

### Adição ($+$)

In [1]:
4+4


8

### Subtração ($-$)

In [3]:
4-4

0

### Multiplicação ($*$)

In [4]:
4*5

20

### Divisão ($/$) e ($//$)
A operação divisão sempre retorna um número de ponto flutuante

In [9]:
4/3


1.3333333333333333

In [10]:
4//3

1

### Exponenciação ($**$)

In [11]:
4**4

256

### Resto da divisão ($\%$)

In [17]:
4%2

0

### Expressões matemáticas

In [14]:
4**4/2

128.0

In [19]:
5+5/2

7.5

In [20]:
15*5/10+35

42.5

### A variável _

No modo interativo, o último resultado impresso é atribuído à variável _

In [21]:
a = 215

In [22]:
b = 352


In [23]:
a + b


567

# 2.2 Variáveis 

### Nomes de variáveis

- Nomes de variáveis pode começar com letras (a - z, A - Z) ou o caractere *underscore* (_):

    > Altura
    >
    > _peso
    
- O restante do nome pode conter letras, números e o caractere "_":

    > nome_da_variavel
    >
    > _valor
    >
    > dia_28_11_
    

- O nomes são *case sensitive*:

    > Nome_Da_Variável $\ne$ nome_da_variavel $\ne$ NOME_DA_VARIAVEL
    
### <font color=red>Observações:
- Existem algumas palavras reservadas da linguagem que não podem ser utilizadas como nomes de variável:

| |Lista de palavras <br>reservadas em Python| |
|:-------------:|:------------:|:-------------:|
| and           | as           | not           | 
| assert        | finally      | or            | 
| break         | for          | pass          | 
| class         | from         | nonlocal      | 
| continue      | global       | raise         | 
| def           | if           | return        | 
| del           | import       | try           | 
| elif          | in           | while         | 
| else          | is           | with          | 
| except        | lambda       | yield         | 
| False         | True         | None          | 

### Declaração de variáveis

### Operadores de atribuição: $=$, $+=$, $-=$, $*=$, $/=$, $**=$, $\%=$, $//=$

In [16]:
ano_atual = 2021
ano_fabricacao = 2003
km_total = 44410.0

# $$km_{média} = \frac {km_{total}}{(Ano_{atual} - Ano_{fabricação})}$$

### Operações com variáveis

In [22]:
ano_atual = 2021
ano_fabricacao = 2003
km_total = 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)

km_total += km_media
km_total

46877.22222222222

In [24]:
ano_atual,ano_fabricacao, km_total = 2021,2003, 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)
km_total += km_media
km_total

46877.22222222222

In [30]:
km_media


1363.6363636363637

### Conclusão:
```
"valor = valor + 1" é equivalente a "valor += 1"
```

### Declaração múltipla

# 2.3 Tipos de dados

Os tipos de dados especificam como números e caracteres serão armazenados e manipulados dentro de um programa. Os tipos de dados básicos do Python são:

1. **Números**
    1. ***int*** - Inteiros
    - ***float*** - Ponto flutuante
- **Booleanos** - Assume os valores True ou False. Essencial quando começarmos a trabalhar com declarações condicionais
- ***Strings*** - Sequência de um ou mais caracteres que pode incluir letras, números e outros tipos de caracteres. Representa um texto.
- **None** - Representa a ausência de valor

### Números

In [25]:
ano_atual

2021

In [26]:
type(ano_atual)

int

In [27]:
km_total

46877.22222222222

In [28]:
type(km_total)

float

### Booleanos

In [29]:
zero_km = True

In [30]:
type(zero_km)

bool

In [31]:
zero_km = False

In [32]:
type(zero_km)



bool

### Strings

In [34]:
nomes_carros = 'Jetta'

In [35]:
type(nomes_carros)

str

In [37]:
carro = '''Nome
idade
Nota
'''

In [38]:
carro

'Nome\nidade\nNota\n'

### None

In [39]:
km = None

In [40]:
type (km)

NoneType

# 2.4 Conversão de tipos

In [45]:
a = 10
b = 10
c = 'Python'
d = 'Maneiro'

In [46]:
type (a)

int

In [47]:
type (b)

int

In [48]:
type (c)

str

In [49]:
type (d)

str

### Conversões de tipo

Funções int(), float(), str()

In [50]:
str(a)

'10'

In [51]:
type (a)

int

In [53]:
c+ str(a) 

'Python10'

In [55]:
var = 3.146565

In [56]:
int (var)

3

# 2.5 Indentação, comentários e formatação de *strings*

### Indentação

Na linguagem Python os programas são estruturados por meio de indentação. Em qualquer linguagem de programação a prática da indentação é bastante útil, facilitando a leitura e também a manutenção do código. Em Python a indentação não é somente uma questão de organização e estilo, mas sim um requisito da linguagem.

In [57]:
ano_atual = 2019
ano_fabricacao = 2019

if (ano_atual == ano_fabricacao):
    print('Verdadeiro')
else:
    print('Falso')

Verdadeiro


### Comentários

Comentários são extremamente importantes em um programa. Consiste em um texto que descreve o que o programa ou uma parte específica do programa está fazendo. Os comentários são ignorados pelo interpretador Python. 

Podemos ter comentários de uma única linha ou de múltiplas linhas.

In [ ]:
# Isto é um comentário
ano_atual = 2019
ano_atual

In [ ]:
# Isto
# é um 
# comentário
ano_atual = 2019
ano_atual

In [ ]:
'''Isto é um
comentário'''
ano_atual = 2019
ano_atual

In [58]:
# Definindo variáveis
ano_atual = 2019
ano_fabricacao = 2019

'''
Estrutura condicional que vamos 
aprender na próxima aula
'''
if (ano_atual == ano_fabricacao):   # Testando se condição é verdadeira
    print('Verdadeiro')
else:                               # Testando se condição é falsa
    print('Falso')

Verdadeiro


### Formatação de *strings*

## *str % valor*
https://docs.python.org/3.6/library/stdtypes.html#old-string-formatting

## *str.format()*

https://docs.python.org/3.6/library/stdtypes.html#str.format

In [67]:
print (('Olá {}!, você comprou o carro {}, com tantos KM {}').format("Rodrigo",'Renault Sandero',  km_total//2))

Olá Rodrigo!, você comprou o carro Renault Sandero, com tantos KM 23438.0


Digite seu nomeRamon
Digite seu carroFordKa
Olá Ramon!, você comprou o carro FordKa, com tantos KM 46877.22222222222


## *f-Strings*

https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings

In [74]:
nome = input(str("Digite seu nome: "))
carro_novo = input(str("Digite seu carro: "))
km_total
print (f'Olá {nome}!, você comprou o carro {carro_novo}, com tantos KM {km_total}')

Digite seu nome: Ramon
Digite seu carro: Ford Ka
Olá Ramon!, você comprou o carro Ford Ka, com tantos KM 46877.22222222222


# <font color=green> 3. TRABALHANDO COM LISTAS
---

# 3.1 Criando listas

Listas são sequências **mutáveis** que são utilizadas para armazenar coleções de itens, geralmente homogêneos. Podem ser construídas de várias formas:
```
- Utilizando um par de colchetes: [ ], [ 1 ]
- Utilizando um par de colchetes com itens separados por vírgulas: [ 1, 2, 3 ]
```

In [79]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

### Lista com tipos de dados variados

In [76]:
Carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 88078.64]
Carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimídia', 'Teto panorâmico', 'Freios ABS'], 106161.94]

In [96]:
Carros = [Carro_1, Carro_2]

In [97]:
Carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

# 3.2 Operações com listas

https://docs.python.org/3.6/library/stdtypes.html#common-sequence-operations

## *x in A*

Retorna **True** se um elemento da lista *A* for igual a *x*.

In [81]:
'Rodas de liga' in Acessorios

True

## *A + B*

Concatena as listas *A* e *B*.

In [84]:
A = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']
B = ['Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

In [86]:
C = A + B

In [87]:
len (C)

8

## *len(A)*

Tamanho da lista A.

In [88]:
len (C)

8

# 3.3 Seleções em listas

## *A[ i ]*

Retorna o i-ésimo item da lista *A*.

<font color=red>**Observação:**</font> Listas têm indexação com origem no zero.

In [94]:
Acessorios[0:-1]

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular']

In [103]:
Carros[0][-2][1]

'Travas elétricas'

## *A[ i : j ]*

Recorta a lista *A* do índice i até o j. Neste fatiamento o elemento com índice i é **incluído** e o elemento com índice j **não é incluído** no resultado.

In [105]:
Acessorios[2:5]

['Piloto automático', 'Bancos de couro', 'Ar condicionado']

In [106]:
Acessorios[2:]

['Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [107]:
letras = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

# 3.4 Métodos de listas

https://docs.python.org/3.6/library/stdtypes.html#mutable-sequence-types

## *A.sort()*

Ordena a lista *A*.

In [108]:
Acessorios.sort()

In [109]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

## *A.append(x)*

Adiciona o elemnto *x* no final da lista *A*.

In [111]:
Acessorios.append('Teto Solar')
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 'Teto Solar',
 'Teto Solar']

## *A.pop(i)*

Remove e retorna o elemento de índice i da lista *A*.

<font color=red>**Observação:**</font> Por *default* o método *pop()* remove e retorna o último elemento de uma lista.

In [114]:
Acessorios.pop()
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [115]:
Acessorios.pop(3)

'Rodas de liga'

## *A.copy()*

Cria uma cópia da lista *A*.

<font color=red>**Observação:**</font> O mesmo resultado pode ser obtido com o seguinte código: 
```
A[:]
```

In [117]:
Acessorios_2 = Acessorios
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [118]:
Acessorios_2 = Acessorios.copy()

In [119]:
Acessorios_2.append('4x4')

In [121]:
Acessorios_2
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

# <font color=green> 4. ESTRUTURAS DE REPETIÇÃO E CONDICIONAIS
---

# 4.1 Instrução *for*

#### Formato padrão

```
for <variável> in <coleção>:
    <instruções>
```

### Loops com listas

In [123]:
for item in Acessorios:
  print(item)

Ar condicionado
Bancos de couro
Piloto automático
Sensor crepuscular
Sensor de chuva
Sensor de estacionamento
Travas elétricas


###  List comprehensions

https://docs.python.org/3.6/tutorial/datastructures.html#list-comprehensions

*range()* -> https://docs.python.org/3.6/library/functions.html#func-range

In [124]:
range (10)

range(0, 10)

In [125]:
list (range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [127]:
for i in range(10):
  
  print(i**2)


0
1
4
9
16
25
36
49
64
81


In [133]:
quadrado = []
for i in range(10):
  quadrado.append(i**2)  
quadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [134]:
[i**2 for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# 4.2 Loops aninhados

In [164]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [163]:
Novos_acessorios = []
for lista in dados:
  for item in lista:
    Novos_acessorios.append(item)
Novos_acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos',
  [...]],
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos',
  [...]],
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos',
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio autom

## *set()*

https://docs.python.org/3.6/library/stdtypes.html#types-set

https://docs.python.org/3.6/library/functions.html#func-set

In [167]:
list(set(Novos_acessorios))

TypeError: ignored

### List comprehensions

In [171]:
list(set([item for lista in dados for item in lista ]))

['Travas elétricas',
 'Câmera de estacionamento',
 'Sensor crepuscular',
 'Ar condicionado',
 'Controle de estabilidade',
 'Piloto automático',
 'Freios ABS',
 'Sensor de estacionamento',
 'Câmbio automático',
 'Vidros elétricos',
 'Teto panorâmico',
 'Painel digital',
 'Sensor de chuva',
 '4 X 4',
 'Rodas de liga',
 'Bancos de couro',
 'Central multimídia']

# 4.3 Instrução *if*

#### Formato padrão

```
if <condição>:
     <instruções caso a condição seja verdadeira>
```

### Operadores de comparação: $==$, $!=$, $>$, $<$, $>=$, $<=$
### e
### Operadores lógicos: $and$, $or$, $not$

In [12]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [181]:
zero_km_Y = [] 
for lista in dados:
  if (lista[2]== True):
    zero_km_Y.append(lista)
print(zero_km_Y)


[['DS5', 2019, True], ['A5', 2019, True]]


In [182]:
zero_km_N = [] 
for lista in dados:
  if (lista[2]== False):
    zero_km_N.append(lista)
print(zero_km_N)

[['Jetta Variant', 2003, False], ['Passat', 1991, False], ['Crossfox', 1990, False], ['Aston Martin DB4', 2006, False], ['Palio Weekend', 2012, False], ['Série 3 Cabrio', 2009, False], ['Dodge Jorney', 2019, False], ['Carens', 2011, False]]


### List comprehensions

In [185]:
[lista for lista in dados if (lista[2]== False)]

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

# 4.4 Instruções *if-else* e *if-elif-else*

#### Formato padrão

```
if <condição>:
    <instruções caso a condição seja verdadeira>
else:
    <instruções caso a condição não seja verdadeira>
```

In [186]:
zero_km_N,zero_km_Y = [] , []
for lista in dados:
  if (lista[2]== False):
    zero_km_N.append(lista)
  else:
    zero_km_Y.append(lista)
print(zero_km_N,zero_km_Y)

[['Jetta Variant', 2003, False], ['Passat', 1991, False], ['Crossfox', 1990, False], ['Aston Martin DB4', 2006, False], ['Palio Weekend', 2012, False], ['Série 3 Cabrio', 2009, False], ['Dodge Jorney', 2019, False], ['Carens', 2011, False]] [['DS5', 2019, True], ['A5', 2019, True]]


In [187]:
dados


[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

#### Formato padrão

```
if <condição 1>:
    <instruções caso a condição 1 seja verdadeira>
elif <condição 2>:
    <instruções caso a condição 2 seja verdadeira>
elif <condição 3>:
    <instruções caso a condição 3 seja verdadeira>
                        .
                        .
                        .
else:
    <instruções caso as condições anteriores não sejam verdadeiras>
```

In [ ]:
print('AND')
print(f'(True and True) o resultado é: {True and True}')
print(f'(True and False) o resultado é: {True and False}')
print(f'(False and True) o resultado é: {False and True}')
print(f'(False and False) o resultado é: {False and False}')

In [ ]:
print('OR')
print(f'(True or True) o resultado é: {True or True}')
print(f'(True or False) o resultado é: {True or False}')
print(f'(False or True) o resultado é: {False or True}')
print(f'(False or False) o resultado é: {False or False}')

In [199]:
dados
A,B,C = [],[],[]
for lista in dados:
  if(lista[1] <= 2000):
    A.append(lista)
  elif(lista[1] > 2000 and lista[1] <= 2010):
    B.append(lista)
  else:
    C.append(lista)
B

[['Jetta Variant', 2003, False],
 ['Aston Martin DB4', 2006, False],
 ['Série 3 Cabrio', 2009, False]]

# <font color=green> 5. NUMPY BÁSICO
---

Numpy é a abreviação de Numerical Python e é um dos pacotes mais importantes para processamento numérico em Python. Numpy oferece a base para a maioria dos pacotes de aplicações científicas que utilizem dados numéricos em Python (estruturas de dados e algoritmos). Pode-se destacar os seguintes recursos que o pacote Numpy contém:

- Um poderoso objeto array multidimensional;
- Funções matemáticas sofisticadas para operações com arrays sem a necessidade de utilização de laços *for*;
- Recursos de algebra linear e geração de números aleatórios

Além de seus óbvios usos científicos, o pacote NumPy também é muito utilizado em análise de dados como um eficiente contêiner multidimensional de dados genéricos para transporte entre diversos algoritmos e bibliotecas em Python.

**Versão:** 1.16.5

**Instalação:** https://scipy.org/install.html

**Documentação:** https://numpy.org/doc/1.16/

### Pacotes

Existem diversos pacotes Python disponíveis para download na internet. Cada pacote tem como objetivo a solução de determinado tipo de problema e para isso são desenvolvidos novos tipos, funções e métodos.

Alguns pacotes são bastante utilizados em um contexto de ciência de dados como por exemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Alguns pacotes não são distribuídos com a instalação default do Python. Neste caso devemos instalar os pacotes que necessitamos em nosso sistema para podermos utilizar suas funcionalidades.

### Importando todo o pacote

In [5]:
import numpy as np 

https://numpy.org/doc/1.16/reference/generated/numpy.arange.html

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando todo o pacote e atribuindo um novo nome 

### Importando parte do pacote

In [4]:
from numpy import arange
arange (10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5.1 Criando arrays Numpy

In [7]:
km = np.array([100,2300,500,4957])
km

array([ 100, 2300,  500, 4957])

### A partir de listas

https://numpy.org/doc/1.16/user/basics.creation.html

https://numpy.org/doc/1.16/user/basics.types.html

### A partir de dados externos

https://numpy.org/doc/1.16/reference/generated/numpy.loadtxt.html

In [10]:
km = np.loadtxt(fname='carros-km.txt', dtype=int)
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [14]:
Acessorios = np.array(dados)
Acessorios


array([['Jetta Variant', '2003', 'False'],
       ['Passat', '1991', 'False'],
       ['Crossfox', '1990', 'False'],
       ['DS5', '2019', 'True'],
       ['Aston Martin DB4', '2006', 'False'],
       ['Palio Weekend', '2012', 'False'],
       ['A5', '2019', 'True'],
       ['Série 3 Cabrio', '2009', 'False'],
       ['Dodge Jorney', '2019', 'False'],
       ['Carens', '2011', 'False']], dtype='<U16')

### Arrays com duas dimensões

In [ ]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

### Comparando desempenho com listas

In [15]:
np_array = np.arange(1000000)

In [22]:
py_list = list(range(1000000))

In [18]:
%time for _ in range(100): np_array *= 2

CPU times: user 53.2 ms, sys: 690 µs, total: 53.9 ms
Wall time: 56.1 ms


In [24]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

CPU times: user 9.81 s, sys: 3.18 s, total: 13 s
Wall time: 13 s


# 5.2 Operações aritméticas com arrays Numpy

### Operações entre arrays e constantes

In [27]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [28]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [30]:
idade = 2021 - anos
idade

array([18, 30, 31,  2, 15])

### Operações entre arrays

In [33]:
km_media = km / idade
km_media

array([2467.22222222,  190.4       , 1197.51612903,    0.        ,
       1717.13333333])

### Operações com arrays de duas dimensões

In [115]:
dados = np.array([km,anos])

In [36]:
dados.shape

(2, 5)

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [41]:
dados[0][0]

2003.0

In [42]:
km_media = dados[0] / (2021-dados[1])

In [43]:
km_media

array([2467.22222222,  190.4       , 1197.51612903,    0.        ,
       1717.13333333])

# 5.3 Seleções com arrays Numpy

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexação 

<font color=red>**Observação:**</font> A indexação tem origem no zero.

In [44]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
contador[0]

0

In [47]:
item = 6
index = item -1
contador[index]

5

In [48]:
dados [1][2]

1990.0

In [49]:
dados [1,2]

1990.0

## <font color=green>**Dica:**</font>
### *ndarray[ linha ][ coluna ]* ou *ndarray[ linha, coluna ]*

 ### Fatiamentos
 
A sintaxe para realizar fatiamento em um array Numpy é $i : j : k$ onde $i$ é o índice inicial, $j$ é o índice de parada, e $k$ é o indicador de passo ($k\neq0$)
 
<font color=red>**Observação:**</font> Nos fatiamentos (*slices*) o item com índice i é **incluído** e o item com índice j **não é incluído** no resultado.

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [52]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
dados


array([['Roberto', 'casado', 'masculino'],
       ['Sheila', 'solteiro', 'feminino'],
       ['Bruno', 'solteiro', 'masculino'],
       ['Rita', 'casado', 'feminino']], dtype='<U9')

In [83]:
dados [:,1:3]

array([[ 5712., 37123.],
       [ 1991.,  1990.]])

In [88]:
dados [:,1:3][0] / (2021- dados[1])

ValueError: ignored

In [89]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [90]:
contador[contador > 5]

array([6, 7, 8, 9])

In [98]:
dados[1] > 2000


array([ True, False, False,  True,  True])

In [100]:
dados[:,dados[1] > 2000] 

ValueError: ignored

In [112]:
dados = np.array(
    [
        ['Roberto', 'casado', 'masculino'],
        ['Sheila', 'solteiro', 'feminino'],
        ['Bruno', 'solteiro', 'masculino'],
        ['Rita', 'casado', 'feminino']
    ]
)
dados[0::2,:1]

array([['Roberto'],
       ['Bruno']], dtype='<U9')

### Indexação com array booleano

<font color=red>**Observação:**</font> Seleciona um grupo de linhas e colunas segundo os rótulos ou um array booleano.

# 5.4 Atributos e métodos de arrays Numpy

### Atributos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-attributes

In [116]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

## *ndarray.shape*

Retorna uma tupla com as dimensões do array.

In [117]:
dados.shape

(2, 5)

## *ndarray.ndim*

Retorna o número de dimensões do array.

In [118]:
dados.ndim

2

## *ndarray.size*

Retorna o número de elementos do array.

In [119]:
dados.size

10

## *ndarray.dtype*

Retorna o tipo de dados dos elementos do array.

In [120]:
dados.dtype

dtype('float64')

## *ndarray.T*

Retorna o array transposto, isto é, converte linhas em colunas e vice versa.

In [121]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [122]:
dados.transpose

<function ndarray.transpose>

### Métodos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-methods

## *ndarray.tolist()*

Retorna o array como uma lista Python.

In [123]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

## *ndarray.reshape(shape[, order])*

Retorna um array que contém os mesmos dados com uma nova forma.

In [124]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
contador.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [126]:
contador.reshape((5,2), order = 'C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [127]:
contador.reshape((5,2), order = 'F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [128]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [130]:
info_car = km + anos
info_car

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [137]:
np.array(info_car).reshape((5,2), order='F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

## *ndarray.resize(new_shape[, refcheck])*

Altera a forma e o tamanho do array.

In [138]:
dados_new = dados.copy()

In [140]:
dados_new.resize((3,5))
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [142]:
dados_new[2] = dados_new[0] / (2021 - dados_new[1])
dados_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2467.22222222,   190.4       ,  1197.51612903,     0.        ,
         1717.13333333]])

# 5.5 Estatísticas com arrays Numpy

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#calculation

e

https://numpy.org/doc/1.16/reference/routines.statistics.html

e

https://numpy.org/doc/1.16/reference/routines.math.html

In [143]:
anos = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

In [ ]:
dataset = np.column_stack((anos,km,valor))
dataset

https://numpy.org/doc/1.16/reference/generated/numpy.column_stack.html

## *np.mean()*

Retorna a média dos elementos do array ao longo do eixo especificado.

In [ ]:
np.mean(dataset, axis = 1)

In [149]:
np.mean(dataset[:, 1])

44499.41472868217

## *np.std()*

Retorna o desvio padrão dos elementos do array ao longo do eixo especificado.

In [152]:
np.std(dataset[:,2])

29754.101150388564

## *ndarray.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [153]:
dataset.sum(axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [155]:
dataset[:, 1].sum()

11480849.0

## *np.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [156]:
idades = np.array([10, 23, 45, 34, 25])